# NOT USED YET

# TODO:
# Add GITHUB_TOKEN to Travis
# Add https://goreleaser.com/#continous_integration

builds:
  - 
    binary: fider
    ldflags: -s -w -X main.version={{.Version}} -X main.buildtime={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    darwin: macOS
  files:
    - LICENSE
    - favicon.ico
    - migrations/*
    - views/*
#    - dist/*  -> Rename output?

release:
  name_template: "{{.Version}}"