# TODO: Cache NPM install
# TODO: Push docker images (only on master)

version: 2
jobs:
  build:
    docker:
      - image: getfider/circleci:0.0.4
    working_directory: /go/src/github.com/getfider/fider
    steps:
      - checkout
      - restore_cache:
          keys:
            - fider-v1-npm-{{ checksum "package-lock.json" }}
      - run:
          name: npm install
          command: if [ ! -d "./node_modules" ]; then npm install; fi
      - run: make lint
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build
      - save_cache:
          key: fider-v1-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
  test:
    docker:
      - image: getfider/circleci:0.0.4
      - image: postgres:9.6.2
    working_directory: /go/src/github.com/getfider/fider
    steps:
      - checkout
      - run:
          name: setup postgres
          command: |
            mkdir dist
            for i in 1 2 3 4 5; do psql -h localhost -p 5432 -U postgres -c "CREATE DATABASE fider_ci" && break || sleep 2; done
            for i in 1 2 3 4 5; do psql -h localhost -p 5432 -U postgres -c "CREATE EXTENSION pg_trgm" -d fider_ci && break || sleep 2; done
            for i in 1 2 3 4 5; do psql -h localhost -p 5432 -U postgres -c "CREATE USER fider_ci WITH PASSWORD 'fider_ci_pw'" && break || sleep 2; done
      - run: DATABASE_URL=postgres://fider_ci:fider_ci_pw@localhost:5432/fider_ci?sslmode=disable make coverage
      - run: bash <(curl -s https://codecov.io/bash)
  push:
    docker:
      - image: getfider/circleci:0.0.4
    working_directory: /go/src/github.com/getfider/fider
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: make e2e
workflows:
  version: 2
  all:
    jobs:
      - build
      - test
      - push:
          requires:
            - build
            - test