version: 2
jobs:
  build:
    docker:
      - image: getfider/circleci:0.0.2
      - image: postgres:9.6.2
    working_directory: /go/src/github.com/getfider/fider
    steps:
      - checkout
      - run: psql -h localhost -p 5432 -c "CREATE DATABASE fider_ci;"
      - run: psql -h localhost -p 5432 -c "CREATE EXTENSION pg_trgm;" -d fider_ci
      - run: psql -h localhost -p 5432 -c "CREATE USER fider_ci WITH PASSWORD 'fider_ci_pw';"
      - run: npm install
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build
      - run: make link
      - run: DATABASE_URL=postgres://fider_ci:fider_ci_pw@localhost:5432/fider_ci?sslmode=disable make coverage


# Todo: better naming for commands
