# version: 2
# jobs:
#   build:
#     docker:
#       - image: getfider/circleci:0.0.4
#       - image: circleci/postgres:9.6.2
#         environment:
#         - POSTGRES_USER: root
#         - POSTGRES_DB: root
#     working_directory: /go/src/github.com/getfider/fider
#     steps:
#       - checkout
#       - run: npm install
#       - run: make lint
#       - run:
#           name: setup database
#           command: |
#             psql -h localhost -p 5432 -U root -c "CREATE DATABASE fider_ci;"
#             psql -h localhost -p 5432 -U root -c "CREATE EXTENSION pg_trgm;" -d fider_ci
#             psql -h localhost -p 5432 -U root -c "CREATE USER fider_ci WITH PASSWORD 'fider_ci_pw';"
#       - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build
#       - run: DATABASE_URL=postgres://fider_ci:fider_ci_pw@localhost:5432/fider_ci?sslmode=disable make coverage

version: 2
jobs:
  build:
    docker:
      - image: getfider/circleci:0.0.4
    working_directory: /go/src/github.com/getfider/fider
    steps:
      - checkout
      - run: npm install
      - run: make lint
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build
  test:
    docker:
      - image: getfider/circleci:0.0.4
      - image: postgres:9.6.2
    working_directory: /go/src/github.com/getfider/fider
    steps:
      - checkout
      - run:
          name: wait for postgres
          command: | 
            dockerize -wait tcp://localhost:5432 -timeout 1m
            ./scripts/retry.sh psql -h localhost -p 5432 -U postgres -d postgres -c \"SELECT current_timestamp\"
      - run:
          name: setup postgres
          command: |
            mkdir dist
            psql -h localhost -p 5432 -U postgres -c "CREATE DATABASE fider_ci"
            psql -h localhost -p 5432 -U postgres -c "CREATE EXTENSION pg_trgm" -d fider_ci
            psql -h localhost -p 5432 -U postgres -c "CREATE USER fider_ci WITH PASSWORD 'fider_ci_pw'"
      - run: DATABASE_URL=postgres://fider_ci:fider_ci_pw@localhost:5432/fider_ci?sslmode=disable make coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test