name: fider

on: [push]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v1

      - name: install go 1.13.3
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.3'

      - name: install go dependencies
        run: go mod download

      - name: install cli tools
        run: |
          echo "::set-env name=GOPATH::$HOME/go"
          echo "::set-env name=GOBIN::$(go env GOPATH)/bin"
          echo "::add-path::$HOME/go"
          echo "::add-path::$(go env GOPATH)/bin"
          go install github.com/joho/godotenv/cmd/godotenv
          go install github.com/magefile/mage

      - name: install node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm ci
      - run: printenv
      - run: which godotenv
      - run: which mage
      - run: mage test:ui