name: fider

on: [push]

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    container:
      image: getfider/circleci:0.0.21

    steps:
      - name: checkout code
        uses: actions/checkout@v1
      - run: go mod download
      - run: npm ci
      - run: mage lint
      - run: mage test:ui
      - run: mage build:docker